#!/usr/bin/env bash

print_sample() {
  fmt=$1
  sample=$2
  printf "${sample}${fmt}\033[m " "${sample}"
}

trap 'printf "\033[m" && exit' 0 1 2 3 15

echo '[Basic Colors]'
# for attr in {0..9} 21; do
for attr in {0..2}; do
  for text_color in {30..37}; do
    for background_color in {40..47}; do
      print_sample "%-14s" "\033[${attr};${text_color};${background_color}m"
    done
    echo
  done
done
echo

for attr in {0..2}; do
  for text_color in {90..97}; do
    for background_color in {100..107}; do
      print_sample "%-14s" "\033[${attr};${text_color};${background_color}m"
    done
    echo
  done
done
echo

# 8-bit color extension
#  16..231: n = 16 + 36*r + 6*g + 1*b
# 232..252: grayscale (black to white)
echo '[8-bit Colors (6x6x6 Colors and Grayscale)]'
for n in {16..255}; do
  print_sample  "%-14s" "\033[48;5;${n}m"
  (( (n-16) % 6 == 5 )) && echo
done
echo

for n in {16..255}; do
  print_sample "%-14s" "\033[38;5;${n}m"
  (( (n-16) % 6 == 5 )) && echo
done
echo

echo '[24-bit Colors (RGB)]'
rgb_vals=(
203 255 255 255 255
203 255 255 255 255
203 255 255 255 255
203 255 255 255 255
203 255 255 255 255
152 191 204 216 229
100 127 150 178 204
50 63 100 140 178
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
0  0  50 100 153
50 63 100 140 178
100 127 150 178 204
152 191 204 216 229
203 255 255 255 255
203 255 255 255 255
203 255 255 255 255
203 255 255 255 255
)

for ((i=0; i < ${#rgb_vals[@]}; i++)); do
  r=$i
  g=$(( (i + 16*5) % ${#rgb_vals[@]} ))
  b=$(( (i + 8*5) % ${#rgb_vals[@]} ))
  print_sample "%-22s" "\\033[48;2;${rgb_vals[$r]};${rgb_vals[$g]};${rgb_vals[$b]}m"
  (( i % 5 == 4 )) && echo
done
echo

for ((i=0; i < ${#rgb_vals[@]}; i++)); do
  r=$i
  g=$(( (i+ 16*5) % ${#rgb_vals[@]} ))
  b=$(( (i + 8*5) % ${#rgb_vals[@]} ))
  print_sample "%-22s" "\\033[38;2;${rgb_vals[$r]};${rgb_vals[$g]};${rgb_vals[$b]}m"
  (( i % 5 == 4 )) && echo
done
echo

echo '[Other Styles]'
printf "Italic     : "
print_sample "%-14s" "\033[3;30;47m"
print_sample "%-14s" "\033[3;37;40m"
echo

printf "Underline  : "
print_sample "%-14s" "\033[4;30;47m"
print_sample "%-14s" "\033[4;37;40m"
echo
printf "Slow blink : "
print_sample "%-14s" "\033[5;30;47m"
print_sample "%-14s" "\033[5;37;40m"
echo
printf "Rapid blink: "
print_sample "%-14s" "\033[6;30;47m"
print_sample "%-14s" "\033[6;37;40m"
echo
printf "Invert     : "
print_sample "%-14s" "\033[7;30;47m"
print_sample "%-14s" "\033[7;37;40m"
echo
printf "Conceal    : "
print_sample "%-14s" "\033[8;30;47m"
print_sample "%-14s" "\033[8;37;40m"
echo
printf "Strike     : "
print_sample "%-14s" "\033[9;30;47m"
print_sample "%-14s" "\033[9;37;40m"
echo
printf "Underline  : "
print_sample "%-14s" "\033[21;30;47m"
print_sample "%-14s" "\033[21;37;40m"
echo

