#!/usr/bin/env bash

print_sample() {
  fmt=$1
  sample=$2
  printf "${sample}${fmt}\033[0m " "${sample}"
}

echo 'Format: \033[{ATTRIBUTE};{TEXT_COLOR};{BACKGROUND_COLOR}m'
echo

for attr in {0..9} 21; do
  for text_color in {30..37}; do
    for background_color in {40..47}; do
      print_sample "%-14s" "\033[${attr};${text_color};${background_color}m"
    done
    echo
  done
done
